### ISSUE TITLE
potential problems when <p> tags in note

### ISSUE THREAD

**Issue by kemartin2015** [RockefellerArchiveCenter/access-project-script#14]

**Comment by helrond** [comment]
@kemartin2015 Does this issue mean there are known issues when there are <p> tags in notes, or does it mean we need to investigate further to understand whether or not there are problems? If it's the former, let's articulate those problems explicitly in this issue so we know what we're looking for.

**Comment by kemartin2015** [comment]
This issue is resolved by putting note content in quotes when running the initial command.

**Comment by helrond** [comment]
@kemartin2015 is this something we want to account for in the script (i.e. make sure the string is enclosed in quotes)?

**Comment by kemartin2015** [comment]
yes, definitely. I'm planning to update the README with this info. If note content is longer than one word, then it needs to have double quotation marks around it.
