### ISSUE TITLE
If there are two notes within the same file, the script does not modify/delete both of them

### ISSUE THREAD

**Issue by kemartin2015** [RockefellerArchiveCenter/access-project-script#27]
## Describe the bug
If there are two notes within the same file, the script does not modify/delete both

## To reproduce
1. Run the script over a resource record that contains two of the same note type with an identical note. The script will only modify/delete one of these notes.

## Expected behavior
Both notes should be modified/deleted

**Comment by p-galligan** [comment]
Do we expect this issue will come up in reality?

**Comment by kemartin2015** [comment]
@p-galligan I don't think it will come up at all for current uses of the script, but I think it's something to keep in mind.

**Comment by helrond** [comment]
It's not immediately apparent to me why this happens, so I think it would be worth investigating and diagnosing further because it may reveal some undiscovered bugs.
